// <auto-generated />
using System;
using KütüphaneYönetim.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KütüphaneYönetim.Migrations
{
    [DbContext(typeof(KütüphaneDbContextModelSnapshot))]
    partial class KütüphaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KütüphaneYönetim.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Başlık")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MevcutKopya")
                        .HasColumnType("int");

                    b.Property<DateTime>("OluşturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ToplamKopya")
                        .HasColumnType("int");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("KütüphaneYönetim.Models.Üye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OluşturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNumarası")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Üyeler");
                });

            modelBuilder.Entity("KütüphaneYönetim.Models.ÖdünçKaydı", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KitapId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("İadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ÖdünçTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ÜyeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.HasIndex("ÜyeId");

                    b.ToTable("ÖdünçKayıtları");
                });

            modelBuilder.Entity("KütüphaneYönetim.Models.ÖdünçKaydı", b =>
                {
                    b.HasOne("KütüphaneYönetim.Models.Kitap", "Kitap")
                        .WithMany("ÖdünçKayıtları")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KütüphaneYönetim.Models.Üye", "Üye")
                        .WithMany("ÖdünçKayıtları")
                        .HasForeignKey("ÜyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kitap");

                    b.Navigation("Üye");
                });

            modelBuilder.Entity("KütüphaneYönetim.Models.Kitap", b =>
                {
                    b.Navigation("ÖdünçKayıtları");
                });

            modelBuilder.Entity("KütüphaneYönetim.Models.Üye", b =>
                {
                    b.Navigation("ÖdünçKayıtları");
                });
#pragma warning restore 612, 618
        }
    }
}
